jobs:
  rancher_job:
    runs-on: ubuntu-latest
    steps:
      - name: Rancher Action
        uses: colbyhill21/Rancher-Action@1.1
        with:
          args: '"get pods"'
          token: ${{ secrets.RANCHER_TOKEN }}
          context: ${{ secrets.RANCHER_CONTEXT }}
          url: ${{ secrets.RANCHER_URL }}
